#!/usr/bin/env python
# encoding: utf-8

import argparse
import loadimpact
import requests
from apiwrapper.handler import JMXHandler


if __name__=='__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('jmx_file_path')
    args = parser.parse_args()
    try:
        handler = JMXHandler(args.jmx_file_path)
        scenario_id = handler.create_scenario()
        config_id = handler.create_test_config(scenario_id)
        print 'Test config with id %s created.' % config_id
    except requests.exceptions.HTTPError as exc:
        print exc.message
    except IOError as ioerr:
        print '{strerror}: {filename}'.format(
            strerror=ioerr.strerror,
            filename=ioerr.filename
        )
