#!/usr/bin/env python
# encoding: utf-8

import argparse
import requests
import jmxextractor
from apiwrapper.handler import JMXHandler
from apiwrapper import exceptions


if __name__=='__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('jmx_file_path')
    args = parser.parse_args()
    try:
        handler = JMXHandler(args.jmx_file_path)
    except jmxextractor.exceptions.ExtractorException as exc:
        print exc.message
    else:
        try:
            scenario_id = handler.create_scenario()
            config_id = handler.create_test_config(scenario_id)
        except requests.exceptions.HTTPError as exc:
            print exc.message
        except (
            exceptions.BadRequestException, exceptions.MissingAPITokenException
        ) as exc:
            print exc.message
        except IOError as ioerr:
            print '{strerror}: {filename}'.format(
                strerror=ioerr.strerror,
                filename=ioerr.filename
            )
        else:
            print 'Test config with id %s created.' % config_id
